//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class XboxLiveSubmissionProject {
    
    private XboxLiveSubmissionProjectGameConfigProject gameConfigProjectField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProject GameConfigProject {
        get {
            return this.gameConfigProjectField;
        }
        set {
            this.gameConfigProjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProject {
    
    private XboxLiveSubmissionProjectGameConfigProjectProductInformation productInformationField;
    
    private XboxLiveSubmissionProjectGameConfigProjectLocalizedStrings localizedStringsField;
    
    private XboxLiveSubmissionProjectGameConfigProjectPresence presenceField;
    
    private XboxLiveSubmissionProjectGameConfigProjectProperties propertiesField;
    
    private XboxLiveSubmissionProjectGameConfigProjectContexts contextsField;
    
    private XboxLiveSubmissionProjectGameConfigProjectGameModes gameModesField;
    
    private XboxLiveSubmissionProjectGameConfigProjectImages imagesField;
    
    private XboxLiveSubmissionProjectGameConfigProjectGamerPictures gamerPicturesField;
    
    private XboxLiveSubmissionProjectGameConfigProjectAchievements achievementsField;
    
    private XboxLiveSubmissionProjectGameConfigProjectMatchmaking matchmakingField;
    
    private string clsidField;
    
    private string nameField;
    
    private string titleNameField;
    
    private string multiplayerField;
    
    private string projectVersionField;
    
    private string titleIdField;
    
    private string titleTypeField;
    
    private string schemaVersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectProductInformation ProductInformation {
        get {
            return this.productInformationField;
        }
        set {
            this.productInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectLocalizedStrings LocalizedStrings {
        get {
            return this.localizedStringsField;
        }
        set {
            this.localizedStringsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectPresence Presence {
        get {
            return this.presenceField;
        }
        set {
            this.presenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectProperties Properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectContexts Contexts {
        get {
            return this.contextsField;
        }
        set {
            this.contextsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectGameModes GameModes {
        get {
            return this.gameModesField;
        }
        set {
            this.gameModesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectImages Images {
        get {
            return this.imagesField;
        }
        set {
            this.imagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectGamerPictures GamerPictures {
        get {
            return this.gamerPicturesField;
        }
        set {
            this.gamerPicturesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectAchievements Achievements {
        get {
            return this.achievementsField;
        }
        set {
            this.achievementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectMatchmaking Matchmaking {
        get {
            return this.matchmakingField;
        }
        set {
            this.matchmakingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string titleName {
        get {
            return this.titleNameField;
        }
        set {
            this.titleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string multiplayer {
        get {
            return this.multiplayerField;
        }
        set {
            this.multiplayerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string projectVersion {
        get {
            return this.projectVersionField;
        }
        set {
            this.projectVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string titleId {
        get {
            return this.titleIdField;
        }
        set {
            this.titleIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string titleType {
        get {
            return this.titleTypeField;
        }
        set {
            this.titleTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectProductInformation {
    
    private XboxLiveSubmissionProjectGameConfigProjectProductInformationRating[] ratingField;
    
    private XboxLiveSubmissionProjectGameConfigProjectProductInformationGenre genreField;
    
    private XboxLiveSubmissionProjectGameConfigProjectProductInformationFeature[] featureField;
    
    private XboxLiveSubmissionProjectGameConfigProjectProductInformationPlatform platformField;
    
    private string offlinePlayersMaxField;
    
    private string systemLinkPlayersMaxField;
    
    private string livePlayersMaxField;
    
    private string publisherStringIdField;
    
    private string developerStringIdField;
    
    private string sellTextStringIdField;
    
    private string genreTextStringIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rating", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectProductInformationRating[] Rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectProductInformationGenre Genre {
        get {
            return this.genreField;
        }
        set {
            this.genreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Feature", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectProductInformationFeature[] Feature {
        get {
            return this.featureField;
        }
        set {
            this.featureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectProductInformationPlatform Platform {
        get {
            return this.platformField;
        }
        set {
            this.platformField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string offlinePlayersMax {
        get {
            return this.offlinePlayersMaxField;
        }
        set {
            this.offlinePlayersMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string systemLinkPlayersMax {
        get {
            return this.systemLinkPlayersMaxField;
        }
        set {
            this.systemLinkPlayersMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string livePlayersMax {
        get {
            return this.livePlayersMaxField;
        }
        set {
            this.livePlayersMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string publisherStringId {
        get {
            return this.publisherStringIdField;
        }
        set {
            this.publisherStringIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string developerStringId {
        get {
            return this.developerStringIdField;
        }
        set {
            this.developerStringIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sellTextStringId {
        get {
            return this.sellTextStringIdField;
        }
        set {
            this.sellTextStringIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string genreTextStringId {
        get {
            return this.genreTextStringIdField;
        }
        set {
            this.genreTextStringIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectProductInformationRating {
    
    private string ratingSystemIdField;
    
    private string ratingIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ratingSystemId {
        get {
            return this.ratingSystemIdField;
        }
        set {
            this.ratingSystemIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ratingId {
        get {
            return this.ratingIdField;
        }
        set {
            this.ratingIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectProductInformationGenre {
    
    private string genreIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string genreId {
        get {
            return this.genreIdField;
        }
        set {
            this.genreIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectProductInformationFeature {
    
    private string nameField;
    
    private string enabledField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectProductInformationPlatform {
    
    private string nameField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectLocalizedStrings {
    
    private XboxLiveSubmissionProjectGameConfigProjectLocalizedStringsSupportedLocale supportedLocaleField;
    
    private XboxLiveSubmissionProjectGameConfigProjectLocalizedStringsLocalizedString[] localizedStringField;
    
    private string clsidField;
    
    private string nextIdField;
    
    private string defaultLocaleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectLocalizedStringsSupportedLocale SupportedLocale {
        get {
            return this.supportedLocaleField;
        }
        set {
            this.supportedLocaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LocalizedString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectLocalizedStringsLocalizedString[] LocalizedString {
        get {
            return this.localizedStringField;
        }
        set {
            this.localizedStringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nextId {
        get {
            return this.nextIdField;
        }
        set {
            this.nextIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultLocale {
        get {
            return this.defaultLocaleField;
        }
        set {
            this.defaultLocaleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectLocalizedStringsSupportedLocale {
    
    private string localeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string locale {
        get {
            return this.localeField;
        }
        set {
            this.localeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectLocalizedStringsLocalizedString {
    
    private XboxLiveSubmissionProjectGameConfigProjectLocalizedStringsLocalizedStringTranslation translationField;
    
    private string presenceField;
    
    private string clsidField;
    
    private string idField;
    
    private string friendlyNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectLocalizedStringsLocalizedStringTranslation Translation {
        get {
            return this.translationField;
        }
        set {
            this.translationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Presence {
        get {
            return this.presenceField;
        }
        set {
            this.presenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string friendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectLocalizedStringsLocalizedStringTranslation {
    
    private string localeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string locale {
        get {
            return this.localeField;
        }
        set {
            this.localeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectPresence {
    
    private XboxLiveSubmissionProjectGameConfigProjectPresencePresenceMode[] presenceModeField;
    
    private string clsidField;
    
    private string nextContextValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PresenceMode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectPresencePresenceMode[] PresenceMode {
        get {
            return this.presenceModeField;
        }
        set {
            this.presenceModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nextContextValue {
        get {
            return this.nextContextValueField;
        }
        set {
            this.nextContextValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectPresencePresenceMode {
    
    private string clsidField;
    
    private string stringIdField;
    
    private string contextValueField;
    
    private string friendlyNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stringId {
        get {
            return this.stringIdField;
        }
        set {
            this.stringIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contextValue {
        get {
            return this.contextValueField;
        }
        set {
            this.contextValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string friendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectProperties {
    
    private XboxLiveSubmissionProjectGameConfigProjectPropertiesProperty[] propertyField;
    
    private string clsidField;
    
    private string nextIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectPropertiesProperty[] Property {
        get {
            return this.propertyField;
        }
        set {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nextId {
        get {
            return this.nextIdField;
        }
        set {
            this.nextIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectPropertiesProperty {
    
    private XboxLiveSubmissionProjectGameConfigProjectPropertiesPropertyFormat formatField;
    
    private string clsidField;
    
    private string idField;
    
    private string stringIdField;
    
    private string dataSizeField;
    
    private string friendlyNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectPropertiesPropertyFormat Format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stringId {
        get {
            return this.stringIdField;
        }
        set {
            this.stringIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataSize {
        get {
            return this.dataSizeField;
        }
        set {
            this.dataSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string friendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectPropertiesPropertyFormat {
    
    private string hoursField;
    
    private string minutesField;
    
    private string secondsField;
    
    private string millisecondsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hours {
        get {
            return this.hoursField;
        }
        set {
            this.hoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minutes {
        get {
            return this.minutesField;
        }
        set {
            this.minutesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string seconds {
        get {
            return this.secondsField;
        }
        set {
            this.secondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string milliseconds {
        get {
            return this.millisecondsField;
        }
        set {
            this.millisecondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectContexts {
    
    private XboxLiveSubmissionProjectGameConfigProjectContextsContext[] contextField;
    
    private string clsidField;
    
    private string nextIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Context", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectContextsContext[] Context {
        get {
            return this.contextField;
        }
        set {
            this.contextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nextId {
        get {
            return this.nextIdField;
        }
        set {
            this.nextIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectContextsContext {
    
    private XboxLiveSubmissionProjectGameConfigProjectContextsContextContextValue contextValueField;
    
    private string clsidField;
    
    private string stringIdField;
    
    private string friendlyNameField;
    
    private string idField;
    
    private string defaultValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectContextsContextContextValue ContextValue {
        get {
            return this.contextValueField;
        }
        set {
            this.contextValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stringId {
        get {
            return this.stringIdField;
        }
        set {
            this.stringIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string friendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultValue {
        get {
            return this.defaultValueField;
        }
        set {
            this.defaultValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectContextsContextContextValue {
    
    private string friendlyNameField;
    
    private string valueField;
    
    private string stringIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string friendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stringId {
        get {
            return this.stringIdField;
        }
        set {
            this.stringIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectGameModes {
    
    private XboxLiveSubmissionProjectGameConfigProjectGameModesGameMode gameModeField;
    
    private string clsidField;
    
    private string defaultValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectGameModesGameMode GameMode {
        get {
            return this.gameModeField;
        }
        set {
            this.gameModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultValue {
        get {
            return this.defaultValueField;
        }
        set {
            this.defaultValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectGameModesGameMode {
    
    private string friendlyNameField;
    
    private string valueField;
    
    private string stringIdField;
    
    private string drawProbabilityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string friendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stringId {
        get {
            return this.stringIdField;
        }
        set {
            this.stringIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string drawProbability {
        get {
            return this.drawProbabilityField;
        }
        set {
            this.drawProbabilityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectImages {
    
    private XboxLiveSubmissionProjectGameConfigProjectImagesImage[] imageField;
    
    private string clsidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Image", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectImagesImage[] Image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectImagesImage {
    
    private string pathField;
    
    private string idField;
    
    private string friendlyNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string friendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectGamerPictures {
    
    private string clsidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectAchievements {
    
    private XboxLiveSubmissionProjectGameConfigProjectAchievementsAchievement[] achievementField;
    
    private string clsidField;
    
    private string nextIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Achievement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectAchievementsAchievement[] Achievement {
        get {
            return this.achievementField;
        }
        set {
            this.achievementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nextId {
        get {
            return this.nextIdField;
        }
        set {
            this.nextIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectAchievementsAchievement {
    
    private string clsidField;
    
    private string idField;
    
    private string titleStringIdField;
    
    private string descriptionStringIdField;
    
    private string showUnachievedField;
    
    private string achievementTypeField;
    
    private string friendlyNameField;
    
    private string credField;
    
    private string imageIdField;
    
    private string unachievedStringIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string titleStringId {
        get {
            return this.titleStringIdField;
        }
        set {
            this.titleStringIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string descriptionStringId {
        get {
            return this.descriptionStringIdField;
        }
        set {
            this.descriptionStringIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string showUnachieved {
        get {
            return this.showUnachievedField;
        }
        set {
            this.showUnachievedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string achievementType {
        get {
            return this.achievementTypeField;
        }
        set {
            this.achievementTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string friendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cred {
        get {
            return this.credField;
        }
        set {
            this.credField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string imageId {
        get {
            return this.imageIdField;
        }
        set {
            this.imageIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unachievedStringId {
        get {
            return this.unachievedStringIdField;
        }
        set {
            this.unachievedStringIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectMatchmaking {
    
    private XboxLiveSubmissionProjectGameConfigProjectMatchmakingConstants constantsField;
    
    private XboxLiveSubmissionProjectGameConfigProjectMatchmakingSchema schemaField;
    
    private XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueries queriesField;
    
    private string clsidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectMatchmakingConstants Constants {
        get {
            return this.constantsField;
        }
        set {
            this.constantsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectMatchmakingSchema Schema {
        get {
            return this.schemaField;
        }
        set {
            this.schemaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueries Queries {
        get {
            return this.queriesField;
        }
        set {
            this.queriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectMatchmakingConstants {
    
    private string clsidField;
    
    private string nextIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nextId {
        get {
            return this.nextIdField;
        }
        set {
            this.nextIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectMatchmakingSchema {
    
    private XboxLiveSubmissionProjectGameConfigProjectMatchmakingSchemaAttribute[] attributeField;
    
    private string clsidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectMatchmakingSchemaAttribute[] Attribute {
        get {
            return this.attributeField;
        }
        set {
            this.attributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectMatchmakingSchemaAttribute {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueries {
    
    private XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQuery queryField;
    
    private string clsidField;
    
    private string nextIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQuery Query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nextId {
        get {
            return this.nextIdField;
        }
        set {
            this.nextIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQuery {
    
    private XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQueryParameter[] parametersField;
    
    private XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQueryFilter[] filtersField;
    
    private string sortOperationsField;
    
    private XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQueryReturn[] returnsField;
    
    private string clsidField;
    
    private string idField;
    
    private string friendlyNameField;
    
    private string maxResultsField;
    
    private string typeField;
    
    private string qosProbeField;
    
    private string groupByField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQueryParameter[] Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Filter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQueryFilter[] Filters {
        get {
            return this.filtersField;
        }
        set {
            this.filtersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SortOperations {
        get {
            return this.sortOperationsField;
        }
        set {
            this.sortOperationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQueryReturn[] Returns {
        get {
            return this.returnsField;
        }
        set {
            this.returnsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string friendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxResults {
        get {
            return this.maxResultsField;
        }
        set {
            this.maxResultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string qosProbe {
        get {
            return this.qosProbeField;
        }
        set {
            this.qosProbeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string groupBy {
        get {
            return this.groupByField;
        }
        set {
            this.groupByField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQueryParameter {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQueryFilter {
    
    private string leftField;
    
    private string leftTypeField;
    
    private string opField;
    
    private string rightField;
    
    private string rightTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string left {
        get {
            return this.leftField;
        }
        set {
            this.leftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string leftType {
        get {
            return this.leftTypeField;
        }
        set {
            this.leftTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string op {
        get {
            return this.opField;
        }
        set {
            this.opField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string right {
        get {
            return this.rightField;
        }
        set {
            this.rightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rightType {
        get {
            return this.rightTypeField;
        }
        set {
            this.rightTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XboxLiveSubmissionProjectGameConfigProjectMatchmakingQueriesQueryReturn {
    
    private string idField;
    
    private string typeField;
    
    private string ordinalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ordinal {
        get {
            return this.ordinalField;
        }
        set {
            this.ordinalField = value;
        }
    }
}
