//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repackinator.Localization.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Repackinator.Localization.Language.UserLocale", typeof(UserLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits go to {0}..
        /// </summary>
        internal static string console_application_credits {
            get {
                return ResourceManager.GetString("console.application.credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is not a valid file..
        /// </summary>
        internal static string console_application_input_exception {
            get {
                return ResourceManager.GetString("console.application.input.exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action (Convert, Compare, Info, Checksum, Extract).
        /// </summary>
        internal static string console_application_option_action {
            get {
                return ResourceManager.GetString("console.application.option.action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        internal static string console_application_option_convert_compress {
            get {
                return ResourceManager.GetString("console.application.option.convert.compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file.
        /// </summary>
        internal static string console_application_option_convert_input {
            get {
                return ResourceManager.GetString("console.application.option.convert.input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrub mode (None *default*, Scrub, TrimmedScrub).
        /// </summary>
        internal static string console_application_option_convert_scrub {
            get {
                return ResourceManager.GetString("console.application.option.convert.scrub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait on exit.
        /// </summary>
        internal static string console_application_option_convert_wait {
            get {
                return ResourceManager.GetString("console.application.option.convert.wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this help or for provided action.
        /// </summary>
        internal static string console_application_option_help {
            get {
                return ResourceManager.GetString("console.application.option.help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: Repackinator {0} [options]+.
        /// </summary>
        internal static string console_application_option_usage {
            get {
                return ResourceManager.GetString("console.application.option.usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: Repackinator [options]+.
        /// </summary>
        internal static string console_application_usage {
            get {
                return ResourceManager.GetString("console.application.usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repackinator by EqUiNoX, original xbox utility..
        /// </summary>
        internal static string console_application_utility {
            get {
                return ResourceManager.GetString("console.application.utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repackinator {0}.
        /// </summary>
        internal static string console_application_version {
            get {
                return ResourceManager.GetString("console.application.version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove context menu (need to run as admin)..
        /// </summary>
        internal static string launcher_context_menu_remove_failed {
            get {
                return ResourceManager.GetString("launcher.context-menu.remove.failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu removed..
        /// </summary>
        internal static string launcher_context_menu_removed {
            get {
                return ResourceManager.GetString("launcher.context-menu.removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string logger_level_completed {
            get {
                return ResourceManager.GetString("logger.level.completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string logger_level_done {
            get {
                return ResourceManager.GetString("logger.level.done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string logger_level_error {
            get {
                return ResourceManager.GetString("logger.level.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string logger_level_info {
            get {
                return ResourceManager.GetString("logger.level.info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string logger_level_none {
            get {
                return ResourceManager.GetString("logger.level.none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound.
        /// </summary>
        internal static string logger_level_notfound {
            get {
                return ResourceManager.GetString("logger.level.notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string logger_level_skipped {
            get {
                return ResourceManager.GetString("logger.level.skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        internal static string logger_level_unknown {
            get {
                return ResourceManager.GetString("logger.level.unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string logger_level_warning {
            get {
                return ResourceManager.GetString("logger.level.warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string scandialog_button_cancel {
            get {
                return ResourceManager.GetString("scandialog.button.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        internal static string scandialog_button_cancelling {
            get {
                return ResourceManager.GetString("scandialog.button.cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string scandialog_button_close {
            get {
                return ResourceManager.GetString("scandialog.button.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Log.
        /// </summary>
        internal static string scandialog_button_copy_log {
            get {
                return ResourceManager.GetString("scandialog.button.copy-log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string scandialog_log_table_level {
            get {
                return ResourceManager.GetString("scandialog.log.table.level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string scandialog_log_table_message {
            get {
                return ResourceManager.GetString("scandialog.log.table.message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string scandialog_log_table_time {
            get {
                return ResourceManager.GetString("scandialog.log.table.time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &apos;{0}&apos; contains mixed ISO and CCI..
        /// </summary>
        internal static string scandialog_logger_message_mixed_iso_cci {
            get {
                return ResourceManager.GetString("scandialog.logger.message.mixed-iso-cci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Directories.
        /// </summary>
        internal static string scandialog_progress_searching_directories {
            get {
                return ResourceManager.GetString("scandialog.progress.searching-directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        internal static string scandialog_title {
            get {
                return ResourceManager.GetString("scandialog.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time: {0:00}:{1:00}:{2:00}.
        /// </summary>
        internal static string scandialog_total_time_elapsed {
            get {
                return ResourceManager.GetString("scandialog.total-time-elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals: Warnings = {0}, Errors = {1}, Skipped = {2}, Missing = {3}, Completed = {4}.
        /// </summary>
        internal static string scandialog_totals {
            get {
                return ResourceManager.GetString("scandialog.totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Scanning List (Time Taken {0:00}:{1:00}:{2:00}).
        /// </summary>
        internal static string scanner_log_completed {
            get {
                return ResourceManager.GetString("scanner.log.completed", resourceCulture);
            }
        }
    }
}
